### ISSUE TITLE
Documenting request headers

### ISSUE THREAD

**Issue by hassankhan** [temando/serverless-openapi-documentation#11]
It doesn't seem as though the plugin can upload `requestHeaders` for functions (and possibly `authorizers` under the main `documentation` section, at least from reading the docs.

**Comment by nfour** [comment]
Yes this is merely undocumented.

```yaml
    requestHeaders:
      - name: Content-Type
        description: Content Type Header (should always be 'application/json')
        schema: 
          type: string
```
